import type { Grant } from './types';
export const MOCK_GRANTS: Grant[] = [
  {
    id: 'grant-001',
    title: 'Innovate for Impact Challenge',
    funder: 'Tech for Good Foundation',
    description: 'A grant for early-stage startups using technology to solve pressing social issues. We are looking for innovative solutions in education, healthcare, and environmental sustainability.',
    amount: 50000,
    deadline: '2025-09-15T23:59:59Z',
    url: 'https://example.com/grant1',
    category: 'Technology',
  },
  {
    id: 'grant-002',
    title: 'Community Arts Project Grant',
    funder: 'National Endowment for the Arts',
    description: 'Funding for community-based arts projects that foster creativity, engagement, and cultural expression. Projects can include murals, workshops, and public performances.',
    amount: 15000,
    deadline: '2025-10-31T23:59:59Z',
    url: 'https://example.com/grant2',
    category: 'Arts & Culture',
  },
  {
    id: 'grant-003',
    title: 'Green Planet Research Fund',
    funder: 'Global Environmental Institute',
    description: 'Supports academic research focused on climate change mitigation, biodiversity conservation, and renewable energy technologies. Open to post-doctoral researchers.',
    amount: 120000,
    deadline: '2025-11-20T23:59:59Z',
    url: 'https://example.com/grant3',
    category: 'Environmental',
  },
  {
    id: 'grant-004',
    title: 'Future Leaders Scholarship',
    funder: 'Bright Minds Scholarship Fund',
    description: 'A scholarship for undergraduate students demonstrating exceptional leadership potential and academic excellence in STEM fields. Requires a minimum 3.5 GPA.',
    amount: 25000,
    deadline: '2026-01-10T23:59:59Z',
    url: 'https://example.com/grant4',
    category: 'Education',
  },
  {
    id: 'grant-005',
    title: 'Small Business Revitalization Grant',
    funder: 'Main Street America Initiative',
    description: 'Financial assistance for small businesses in historic downtown districts to help with facade improvements, marketing, and operational costs. Must be in a designated district.',
    amount: 10000,
    deadline: '2025-08-30T23:59:59Z',
    url: 'https://example.com/grant5',
    category: 'Business',
  },
  {
    id: 'grant-006',
    title: 'Medical Innovation Fellowship',
    funder: 'Healthcare Pioneers Association',
    description: 'A one-year fellowship for medical professionals to develop and prototype innovative medical devices or digital health solutions. Includes mentorship and lab access.',
    amount: 75000,
    deadline: '2025-12-01T23:59:59Z',
    url: 'https://example.com/grant6',
    category: 'Healthcare',
  },
  {
    id: 'grant-007',
    title: 'Rural Education Access Program',
    funder: 'Education Equity Alliance',
    description: 'Grants for non-profits working to improve educational resources and internet access for students in rural and underserved communities.',
    amount: 40000,
    deadline: '2025-10-05T23:59:59Z',
    url: 'https://example.com/grant7',
    category: 'Education',
  },
  {
    id: 'grant-008',
    title: 'Sustainable Agriculture Grant',
    funder: 'Future of Farming Org',
    description: 'Funding for farmers and agricultural researchers implementing sustainable and regenerative farming practices. Projects focusing on soil health are prioritized.',
    amount: 30000,
    deadline: '2025-09-22T23:59:59Z',
    url: 'https://example.com/grant8',
    category: 'Environmental',
  },
  {
    id: 'grant-009',
    title: 'Emerging Playwrights Award',
    funder: 'The Stage Door Society',
    description: 'An award and production grant for an unproduced play by an emerging playwright. The winning play will receive a full production at our partner theater.',
    amount: 20000,
    deadline: '2026-02-15T23:59:59Z',
    url: 'https://example.com/grant9',
    category: 'Arts & Culture',
  },
];